export enum MapPointCategory {
    PLACE = "PLACE",
    EVENT = "EVENT"
}

export enum IconType {
    ENTERTAINMENT = "entertainment",
    MUSEUM = "museum",
    PAVILION = "pavilion",
    ENTRANCE = "entrance",
    RESTAURANT = "restaurant",
    GREEN_ZONE = "green-zone",
    INFO = "info",
    SPORTS_GROUND = "sports-ground",
    FIRST_AID = "first-aid",
    HIRE = "hire",
    FOUNTAIN = "fountain",
    WORKSHOP = "workshop",
    READING_ROOM = "Reading-room",
    PLAYGROUND = "playground",
    SOUVENIRS = "souvenirs",
    PICNIC = "picnic",
    POND = "pond",
    WALKWAY = "walkway",
    TEMPLE = "temple",
    MONUMENT = "monument",
    OTHER = "other",
    SQUARE = "square",
    TICKET = "ticket",
    RIDES = "rides",
    WC = "wc",
    VENDING = "vending",
    ATM = "atm",
    TAXI = "taxi",
    ENTRY = "entry",
    PARKING = "parking",
    EXCURSION = "excursion",
    EXHIBITION = "exhibition",
    MASTERCLASS = "masterclass",
    ONLINE = "online",
    SHOW_MUSIC = "show-music",
    CHILDREN = "children",
    MOVIE = "movie",
    EDUCATION = "education",
    QUEST = "quest",
    COMBO = "combo"
}
